import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <title>Bimbel Pintar - Belajar Jadi Juara!</title>
        <meta name="description" content="Bimbel Pintar siap membantu kamu lulus ujian dengan nilai terbaik! Program intensif, tutor berpengalaman, dan metode belajar efektif." />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://bimbelpintar.vercel.app/" />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
